#!/bin/bash
# Add updateTimer and onTimerExpire functions before startTimer

file="custom_components/beatsy/www/js/ui-player.js"

# Check if updateTimer already exists
if grep -q "function updateTimer()" "$file"; then
    echo "✓ updateTimer function already exists"
else
    # Find the line before "function startTimer" and insert new functions there
    awk '/^function startTimer\(/ {
        print "/**"
        print " * Story 8.5 Task 1: Update timer display with remaining time"
        print " * AC-1: Remaining seconds displayed prominently (e.g., \"28s\")"
        print " * AC-3: Timer calculated client-side from started_at timestamp"
        print " * AC-5: Color changes to red when < 10 seconds remaining"
        print " * AC-6: Timer accuracy within ±1 second of server time"
        print " * @returns {number} Remaining seconds (for testing/validation)"
        print " */"
        print "function updateTimer() {"
        print "    const timerDisplay = document.getElementById('"'"'timer'"'"');"
        print "    if (!timerDisplay) {"
        print "        console.error('"'"'Timer display element not found'"'"');"
        print "        return 0;"
        print "    }"
        print ""
        print "    // AC-3: Calculate remaining time from server timestamp"
        print "    const now = Date.now();"
        print "    const elapsed = now - roundStartedAt;"
        print "    const remaining = Math.max(0, timerDuration - Math.floor(elapsed / 1000));"
        print ""
        print "    // AC-1: Display timer in \"XXs\" format"
        print "    timerDisplay.textContent = `${remaining}s`;"
        print ""
        print "    // AC-5: Color change for urgency (< 10 seconds)"
        print "    if (remaining < 10) {"
        print "        timerDisplay.classList.remove('"'"'text-gray-800'"'"');"
        print "        timerDisplay.classList.add('"'"'text-red-600'"'"');"
        print "    } else {"
        print "        timerDisplay.classList.remove('"'"'text-red-600'"'"');"
        print "        timerDisplay.classList.add('"'"'text-gray-800'"'"');"
        print "    }"
        print ""
        print "    // AC-4: Auto-lock inputs on timer expiration"
        print "    if (remaining <= 0) {"
        print "        clearInterval(timerInterval);"
        print "        timerInterval = null;"
        print "        lockInputs();"
        print "        onTimerExpire();"
        print "        console.log('"'"'⏰ Timer expired, inputs locked'"'"');"
        print "    }"
        print ""
        print "    // Debug logging for accuracy validation (AC-6)"
        print "    if (remaining % 5 === 0 && remaining > 0) {"
        print "        console.log(`[Timer] Remaining: ${remaining}s`);"
        print "    }"
        print ""
        print "    return remaining;"
        print "}"
        print ""
        print "/**"
        print " * Story 8.5 Task 5: Handle timer expiration"
        print " * AC-4: When timer reaches 0, inputs are locked automatically"
        print " * Displays waiting message and triggers expiration logic"
        print " */"
        print "function onTimerExpire() {"
        print "    console.log('"'"'[Timer] Timer expired, waiting for results...'"'"');"
        print ""
        print "    // Display waiting message"
        print "    const timerDisplay = document.getElementById('"'"'timer'"'"');"
        print "    if (timerDisplay && timerDisplay.parentElement) {"
        print "        const waitingMsg = document.createElement('"'"'p'"'"');"
        print "        waitingMsg.id = '"'"'timer-expired-message'"'"';"
        print "        waitingMsg.className = '"'"'text-sm text-gray-600 mt-2 text-center'"'"';"
        print "        waitingMsg.textContent = \"Time'"'"'s up! Waiting for results...\";"
        print ""
        print "        // Remove old message if exists"
        print "        const oldMsg = document.getElementById('"'"'timer-expired-message'"'"');"
        print "        if (oldMsg) {"
        print "            oldMsg.remove();"
        print "        }"
        print ""
        print "        timerDisplay.parentElement.appendChild(waitingMsg);"
        print "    }"
        print ""
        print "    // TODO Story 8.6+: Additional expiration logic (results transition, etc.)"
        print "}"
        print ""
    }
    {print}' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
    echo "✓ Added updateTimer and onTimerExpire functions"
fi
